language: node_js
node_js:
- node
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm config set spin false
- if [ "$TRAVIS_NODE_VERSION" = "8" ]; then
    export NODE_LTS="true";
  fi
- which npx
# don't accidentally use the global npx
- rm $(which npx)
# sometimes this exists
# https://travis-ci.org/ember-cli/ember-cli-update/jobs/475792468#L96
- rm /usr/local/bin/npx || true
# test that we can't find it
- "! which npx"
before_script:
- npm run lint
jobs:
  include:
  - os: osx
  - stage: Deploy
    if: tag IS present
    cache: ignore
    before_install: ignore
    install: ignore
    before_script: ignore
    script: ignore
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
        tags: true
        repo: kellyselden/boilerplate-update
